[package]
name = "dir_to_clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5"
walkdir = "2.3"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
glob = "0.3"
gitignore = "1.0.8"

[dev-dependencies]
tempfile = "3.3"

